### ISSUE TITLE
Seems to be an old version on 'npm install'

### ISSUE THREAD

**Issue by akorp** [fiffty/react-treeview-mui#11]
I am getting an old version with npm install, the one without 	commit 'versions bump'.
Having error with
>>PropTypes via the main React package is deprecated

**Comment by sli** [comment]
Can confirm that this does seem to be the issue. The version I installed from npm just this morning is not usable because it's trying to use React's deprecated PropTypes while the current Git version uses the propTypes module.

`TypeError: _react.PropTypes is undefined`

package.json also differs in the npm release, but lists the same version number as the version on Git (0.1.2). Therefore, one of the package.json files has an incorrect version number. Perhaps the new version was submitted to npm and then rejected it for that?
